### ISSUE TITLE
Issue with account numbers changing over time

### ISSUE THREAD

**Issue by guilhermekirch** [msperlin/GetCVMData#3]
Os códigos das contas para uma mesma empresa podem representar contas (elementos patrimoniais ou de resultados) diferentes ao longo do tempo. Por exemplo:

Companhia: AMBEV (CD_CVM 23264):

1.02.01.03	Contas a Receber (Ano 2017)
1.02.01.03	Aplicações Financeiras Avaliadas ao Custo Amortizado (Anos de 2018 e 2019)

Isso é muito comum nas contas de nível 4 (como no exemplo) ou superior. Ainda mais comum quando se trata do DFC e DVA.

A descrição da conta também varia com o tempo, o que impede usar essa descrição como referência.

**Comment by msperlin** [comment]
Encontre o problema e arrumei. Veja a nova versão aqui: https://github.com/msperlin/GetDFPData2
